### ISSUE TITLE
Decoration Command Crashes Server

### ISSUE THREAD

**Issue by Delphi79** [Grimoric/RunUO.T2A#1]
When I start up the server and use decorate under the wordbuilding commands the server crashes. Here is the crashlog.
`Server Crash Report
===================

RunUO Version 1.0, Build 0.15
Operating System: Microsoft Windows NT 6.2.9200.0
.NET Framework: 4.0.30319.42000
Time: 3/6/2017 12:36:25 AM
Mobiles: 1
Items: 32224
Exception:
System.ArgumentException: Type not found for header: 'ChampionSkullPlatform 0x1'
   at Server.Commands.DecorationList.Read(StreamReader ip)
   at Server.Commands.DecorationList.ReadAll(String path)
   at Server.Commands.Decorate.Generate(String folder, Map[] maps)
   at Server.Commands.Decorate.Decorate_OnCommand(CommandEventArgs e)
   at Server.Commands.CommandSystem.Handle(Mobile from, String text, MessageType type)
   at Server.Gumps.AdminGump.InvokeCommand(String c)
   at Server.Gumps.AdminGump.OnResponse(NetState sender, RelayInfo info)
   at Server.Network.PacketHandlers.DisplayGumpResponse(NetState state, PacketReader pvSrc)
   at Server.Network.MessagePump.HandleReceive(NetState ns)
   at Server.Network.MessagePump.Slice()
   at Server.Core.Main(String[] args)

Clients:
- Count: 1
+ 127.0.0.1: (account = admin) (mobile = 0x1 'Delphi')`

**Comment by Grimoric** [comment]
This have been fixed in build 17. 
ChampionSkullPlatform in star room have been removed, it was not there in T2A,
